import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/storage'

export const dynamic = 'force-dynamic'

function corsHeaders(req: NextRequest) {
  const origin = req.headers.get('origin') || ''
  const allowed = origin.startsWith('chrome-extension://') || origin.includes('localhost')
  return {
    'Access-Control-Allow-Origin':  allowed ? origin : '',
    'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  }
}

export async function OPTIONS(req: NextRequest) {
  return new NextResponse(null, { status: 204, headers: corsHeaders(req) })
}

function buildCookieHeader(cookies: Record<string, string>): string {
  return Object.entries(cookies).map(([k, v]) => `${k}=${v}`).join('; ')
}

export async function POST(req: NextRequest) {
  const { cookies, publication, email, profileVerified, profile } = await req.json()

  if (!cookies || Object.keys(cookies).length === 0)
    return NextResponse.json({ error: 'No se recibieron cookies' }, { status: 400, headers: corsHeaders(req) })

  const cookieHeader = buildCookieHeader(cookies)
  let finalPublication = publication || ''
  let finalEmail       = email || ''
  let finalName        = ''
  let finalAvatar      = ''
  let finalSubCount    = 0
  let finalSubdomain   = ''
  let finalBio         = ''
  let finalHandle      = ''
  let finalLinks       = []
  let finalFollowers   = 0
  let finalLogo        = ''
  let verified         = profileVerified || false

  if (profileVerified && profile) {
    // If extension validated the session, use its payload
    finalPublication = profile?.primaryPublication?.name || publication || ''
    finalEmail       = profile?.email || email || ''
    finalName        = profile?.name || profile?.display_name || ''
    finalAvatar      = profile?.photo_url || profile?.profile_photo_url || ''
    finalSubCount    = profile?.primaryPublication?.subscriber_count || 0
    finalSubdomain   = profile?.primaryPublication?.subdomain || ''
    finalLogo        = profile?.primaryPublication?.logo_url || ''
    finalBio         = profile?.bio || ''
    finalHandle      = profile?.handle || ''
    finalLinks       = profile?.links || []
    finalFollowers   = profile?.followerCount || 0
    verified         = true
  } else {
    try {
      const meRes = await fetch('https://substack.com/api/v1/subscriber/me', {
        headers: {
          'Cookie':     cookieHeader,
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
          'Accept':     'application/json',
          'Referer':    'https://substack.com/',
        }
      })

      if (meRes.ok) {
        const me         = await meRes.json()
        finalPublication = me?.primaryPublication?.name || publication || ''
        finalEmail       = me?.email || email || ''
        finalName        = me?.name || me?.display_name || ''
        finalAvatar      = me?.photo_url || me?.profile_photo_url || ''
        finalSubCount    = me?.primaryPublication?.subscriber_count || 0
        finalSubdomain   = me?.primaryPublication?.subdomain || ''
        verified         = true
      } else {
        return NextResponse.json({
          error: `Substack rechazó las cookies (${meRes.status}). Cierra sesión en substack.com, vuelve a entrar y reconecta.`
        }, { status: 401, headers: corsHeaders(req) })
      }
    } catch (e) {
      return NextResponse.json(
        { error: `No se pudo verificar con Substack: ${String(e)}` },
        { status: 500, headers: corsHeaders(req) }
      )
    }
  }

  // Save everything to relational tables
  const expiresAt = new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString() // ~55 days
  
  try {
    // 1. Upsert User
    const userData: any = {
      substack_user_id: String(profile?.pubId || profile?.primaryPublication?.id || 0),
      substack_slug: finalHandle || finalSubdomain,
      name: finalName,
      handle: finalHandle,
      photo_url: finalAvatar,
      bio: finalBio,
      publication_id: String(profile?.pubId || profile?.primaryPublication?.id || 0),
      subdomain: finalSubdomain,
      subscriber_count: finalSubCount,
      updated_at: new Date().toISOString()
    }

    // Since we don't have a reliable primary key for 'users' yet (UUID generated by DB),
    // we use substack_user_id as the natural key to find/update.
    // However, our storage.ts upsert uses the table's PK.
    // Let's first check if user exists.
    let user = await db.substack.user.get(userData.substack_user_id)
    if (user) {
      userData.id = user.id
    }
    user = await db.substack.user.upsert(userData)

    // 2. Upsert Cookies
    await db.substack.cookies.upsert({
      user_id: user.id,
      substack_sid: cookies['substack.sid'] || '',
      substack_lli: cookies['substack.lli'] || '',
      visit_id: cookies['visit_id'] || '',
      expires_at: expiresAt,
      updated_at: new Date().toISOString()
    })

    // Also update legacy settings for compatibility if needed, but the goal is to move away
    const settings = await db.settings.get()
    await db.settings.save({
      ...settings,
      substackCookie: cookies['substack.sid'] || '', // Keep for now as many parts of code might use it
      substackPublication: finalPublication,
    } as any)

  } catch (dbError) {
    console.error('Error saving to Supabase:', dbError)
    return NextResponse.json({ error: 'Error al guardar en la base de datos' }, { status: 500, headers: corsHeaders(req) })
  }

  return NextResponse.json({
    ok: true, verified,
    publication: finalPublication,
    email:       finalEmail,
    name:        finalName,
    handle:      finalHandle,
    bio:         finalBio,
    avatar:      finalAvatar,
    pubLogo:     finalLogo,
    subCount:    finalSubCount,
    followers:   finalFollowers,
    links:       finalLinks,
    expiresAt,
    cookieNames: Object.keys(cookies),
  }, { headers: corsHeaders(req) })
}

export async function GET(req: NextRequest) {
  const settings = await db.settings.get() as any
  return NextResponse.json({
    connected:   !!(settings.substackCookie || settings.substackCookies),
    publication: settings.substackPublication || '',
    profile:     settings.substackProfile || null,
  }, { headers: corsHeaders(req) })
}

export async function DELETE(req: NextRequest) {
  const settings = await db.settings.get() as any
  const clean    = { ...settings }
  delete clean.substackCookie
  delete clean.substackCookies
  delete clean.substackPublication
  delete clean.substackProfile
  await db.settings.save(clean)
  return NextResponse.json({ ok: true }, { headers: corsHeaders(req) })
}
